In [52]:
import pickle as pkl
import numpy as np
import matplotlib.pyplot as plt
from ais_loader import AISLoader
from jcope_loader import JCOPELoader 
from kalmanLog_loader import KalmanLogLoader
from utils import * 

year = 2015
month = 9
n_day = 4 #nday_month(month)
base_dt = datetime.datetime(year, month, 1, 0, 0, 0)

print(f'Loading data')

kl = KalmanLogLoader(2015, 9, 20)
log_path = r"E:\shunsukeE\result\kalman-shipVar-slice400"
kalman_keys = ['var']
kl.set_path(log_path)


for s in range(0, 1):
    ship_vars = {}
    
    day = n_day-1
    TF = kl.load_kalmanLog_day(1, s, keys=['TF'])['TF']
    start_hour = 0 if day == 1 else 1
    data = kl.load_kalmanLog_day(day, s, keys=kalman_keys)
    
    hour = 22
    dt = datetime.datetime(year, month, day, hour, 0, 0)
    dtidx = date_to_dtidx(base_dt, dt)
    all_mmsi = data['var'][dtidx].keys()
    print(f'Num mmsi: {len(all_mmsi)}') 
    
    for mmsi in all_mmsi:
        ship_vars[mmsi] = []
        
    for day in range(1, n_day):
        print(f's"{s}, day:{day}')
        TF = kl.load_kalmanLog_day(1, s, keys=['TF'])['TF']

        #start_hour = 0 if day == 1 else 1
        start_hour = 1
        try:
            data = kl.load_kalmanLog_day(day, s, keys=kalman_keys)
            for hour in range(start_hour, 23):
                dt = datetime.datetime(year, month, day, hour, 0, 0)
                dtidx = date_to_dtidx(base_dt, dt)
                data['var'][dtidx].keys()

                for mmsi in all_mmsi:
                    if not mmsi in data['var'][dtidx].keys():
                        ship_vars[mmsi].append(np.nan)
                    else:
                        ship_vars[mmsi].append(data['var'][dtidx][mmsi])
        except:
            print(f'error')
    
    for mmsi in all_mmsi:
        ship_var = np.array(ship_vars[mmsi])
        print(f'ship_var shape{ship_var.shape}')

        if np.sum(ship_var!=0.0)!=0:
            x = np.arange(len(ship_var))
            plt.plot(x, ship_var, label=f'{mmsi}')
    #plt.legend()
    plt.xlabel('Time (hour)')
    plt.ylabel('Variance')
    plt.savefig(f'Images/var-{s}.png')

    print(f'saved as Images/var-{s}.png')
    plt.close()


Loading data
Num mmsi: 456
s"0, day:1
s"0, day:2
s"0, day:3
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)


ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
ship_var shape(66,)
saved as Images/var-0.png


In [37]:
data = kl.load_kalmanLog_day(day, s, keys=['var', 'error'])

In [35]:
data['error'][1][431000609]

[array([-1.13388391]),
 array([1.04970193]),
 array([-1.35899452]),
 array([1.04701288]),
 array([-1.05609159]),
 array([1.1982954])]

In [34]:
data['error'][15][431000609]

[array([-1.13388391]),
 array([1.04970193]),
 array([-1.35899452]),
 array([1.04701288]),
 array([-1.05609159]),
 array([1.1982954])]