In [1]:
%matplotlib inline
import datetime
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from filterpy.gh import GHFilter
from numpy.random import randn
import seaborn as sns
from filterpy.common import Saver
from filterpy.kalman import KalmanFilter
from filterpy.common import Q_discrete_white_noise

In [9]:
n = m = 2
kf = KalmanFilter(dim_x=2, dim_z=2)


# F関数, H関数
dt = 0.1
kf.F = np.array([[1, dt], [0, 1]])
kf.H = np.array([[dt*dt/2, 0], [0, dt]])

# システム雑音共分散行列, 観測雑音共分散行列, 共分散行列　TODO
kf.Q = np.eye(2)*0.01
kf.R = np.eye(2)*0.001
kf.P = np.eye(2)

# 初期位置
kf.x = np.array([[0], [0]])
s = Saver(kf)
for i in range(1, 6):
    kf.predict()
    y = np.array([[3], [3]])
    kf.update(y)
    s.save()  # 現在状態を記録する
    print(f"Result of {i}th filter.")
    print(kf.x)

Result of 1th filter.
[[17.4271015 ]
 [27.42850741]]
Result of 2th filter.
[[34.49600927]
 [28.84638968]]
Result of 3th filter.
[[50.98452439]
 [29.39749536]]
Result of 4th filter.
[[66.91938662]
 [29.70110811]]
Result of 5th filter.
[[82.32934654]
 [29.89207905]]
